name: 'Continuous Delivery Development'
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  dependencies:
    name: 'Install dependencies'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@pawnary'
      - uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: |
            ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: 'Deploy to GitHub private npm registry'
    needs:
      - dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@pawnary'
      - uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: |
            ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Deploy to GitHub private npm registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="0.0.0-alpha.${{ github.sha }}"
          git config user.name "ainu"
          git config user.email "ainu@pawnary.cl"
          git remote set-url origin https://x-access-token:${{ secrets.AINU_BOT_TOKEN }}@github.com/pawnary/pawnary-prisma-client.git
          npx lerna version $VERSION --no-git-tag-version --yes
          npx lerna publish from-package --dist-tag next --yes
