name: 'continuous integration'

on:
  pull_request:
    branches:
      - master

jobs:
  dependencies:
    name: 'ci dependencies'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install
  linter:
    name: 'ci linter'
    needs:
      - dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: run linter
        run: npm run lint -- --max-warnings=0
  prettier:
    name: 'ci prettier'
    needs:
      - dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: run prettier
        run: npm run prettier:check
  tests:
    name: 'ci tests'
    needs:
      - dependencies
      - linter
      - prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: run tests
        run: npm run test
