name: 'continuous integration'

on:
  pull_request:
    branches:
      - master

jobs:
  dependencies:
    name: 'ci dependencies'
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@v6
      - &setup-node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@pawnary'
      - &cache-node-modules
        uses: actions/cache@v5
        id: node-modules-cache
        with:
          path: node_modules
          key: |
            ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - name: install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install
  linter:
    name: 'ci linter'
    needs:
      - dependencies
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-node
      - *cache-node-modules
      - name: run linter
        run: npm run lint -- --max-warnings=0
  prettier:
    name: 'ci prettier'
    needs:
      - dependencies
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-node
      - *cache-node-modules
      - name: run prettier
        run: npm run prettier:check
  tests:
    name: 'ci tests'
    needs:
      - dependencies
      - linter
      - prettier
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-node
      - *cache-node-modules
      - name: run tests
        run: npm run test
